# Generated by Django 5.0 on 2023-12-20 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainScrollTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='table-scroll')),
                ('title', models.CharField(max_length=50)),
                ('info', models.CharField(max_length=255)),
                ('price', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'scroll-table',
                'verbose_name_plural': 'scrolls-table',
            },
        ),
    ]
