# Generated by Django 5.0 on 2023-12-20 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_mainscrolltable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainscrolltable',
            name='price',
            field=models.IntegerField(),
        ),
    ]
