# Generated by Django 5.0 on 2023-12-20 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_mainscrolltable_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainscrolltable',
            options={'verbose_name': 'scroll_table', 'verbose_name_plural': 'scrolls_table'},
        ),
    ]
